### ISSUE TITLE
Issue with StarterKit Files

### ISSUE THREAD

**Issue by martyh888** [Azure/enterprise-azure-policy-as-code#116] opened 2023-01-22 15:34 UTC
Issues with StarterKit files where name of definition has spaces

policyDefinitions/Defender/azure-defender-enroll.json

This following throws the error due to spaces and not using "-" instead
```
New-AzPolicyDefinition: /home/vsts/work/1/s/Scripts/Deploy/Deploy-PolicyPlan.ps1:208
Line |
 208 |              $null = New-AzPolicyDefinition @policyDefinition
     |                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | MismatchedPolicyDefinitionName : The policy definition name
     | 'EnableAzureDefenderforResourceType' in the request body does not match
     | the policy definition name 'Enable Azure Defender for Resource Type' in
     | the request uri. CorrelationId: f6e0eade-9bfd-4df6-9863-514d6a534d12
```

Need to fix this

```json
"name": "Enable Azure Defender for Resource Type",
```

And also fix file Definitions/policySetDefinitions/defender-dine-enable-for-subscription-initiative.jsonc to be the same as what the name is changed to above

**Comment by techlake** [comment] 2023-01-22 15:41
This is caused by a bug in Az PowerShell Module 9.2.x. It is fixed in 9.3.0. I will add a big warning to the README.md file tomorrow.

**Comment by martyh888** [comment] 2023-01-22 15:42
Will this also fix this issue
![image](https://user-images.githubusercontent.com/17297403/213924804-80c55a78-f08d-40c6-a845-827ed657e628.png)

**Comment by martyh888** [comment] 2023-01-22 16:01
Thanks all good working now with this change in pipeline

Replaced this line in all occurrences in pipeline


```yaml
azurePowerShellVersion: LatestVersion

with this

preferredAzurePowerShellVersion: "9.3.0"
```

**Comment by techlake** [comment] 2023-01-22 17:31
Great. I'll put that in the README file. Your fix above is a partial fix. The bug in 9.2.x removes all spaces in any of the values. It breaks display names, descriptions, even parameter values in assignments. See https://github.com/Azure/azure-powershell/issues/20407.

**Comment by techlake** [comment] 2023-01-23 18:05
Actually, some are updated, some are still on 9.2.0. Try again tomorrow when all images should be rolled over.

**Closed** 2023-01-23 22:41 UTC
